"""Plotting and visualization utilities."""

# Archetype plots
from arcadia.plotting.archetypes import (
    plot_archetype_embedding,
    plot_archetype_heatmaps,
    plot_archetype_proportions,
    plot_archetype_visualizations,
    plot_archetype_vs_latent_distances,
    plot_archetype_weights,
    plot_batch_archetype_visualization,
    plot_cn_features_correlation,
    plot_cross_modal_archetype_similarity_matrix,
    plot_extreme_archetypes_alignment,
)

# General utilities
from arcadia.plotting.general import (
    compute_opacity_per_cell_type,
    plot_cell_type_distribution,
    plot_data_overview,
    plot_preprocessing_results,
    safe_mlflow_log_figure,
    set_consistent_cell_type_colors,
)

# Post-hoc plots
from arcadia.plotting.post_hoc import (
    generate_cn_umap_plots,
    plot_counterfactual_distribution_histograms,
    plot_grouped_metrics,
    plot_individual_and_combined_umaps,
    plot_latent_space_mixing,
    plot_metrics_by_cell_type,
    plot_morans_i,
    plot_same_modal_vs_counterfactual_rna_differential_expression_and_umap,
    plot_umap_latent_arcadia,
)

# Preprocessing plots
from arcadia.plotting.preprocessing import (
    plot_b_cells_analysis,
    plot_batch_correction_after,
    plot_batch_correction_before,
    plot_count_distribution,
    plot_expression_heatmap,
    plot_expression_heatmaps,
    plot_extreme_archetype_confusion,
    plot_final_alignment_results,
    plot_gene_variance_elbow,
    plot_kneedle_analysis,
    plot_merged_dataset_analysis,
    plot_original_data_umaps,
    plot_original_data_visualizations,
    plot_pca_and_umap,
    plot_protein_analysis,
    plot_protein_umap,
    plot_protein_violin,
    plot_spatial_distance_hist,
    plot_spatial_locations,
    plot_spatial_only_umap,
    plot_umap_visualizations_original_data,
    plot_variance_analysis_processed,
    plot_variance_analysis_raw,
)

# Spatial plots
# Spatial plots
from arcadia.plotting.spatial import (
    plot_elbow_method,
    plot_feature_mean_distributions,
    plot_feature_means_line,
    plot_feature_value_distributions,
    plot_modality_embeddings,
    plot_protein_cn_subset_umaps,
    plot_protein_vs_cn_statistics,
    plot_spatial_clusters,
    plot_spatial_data,
    plot_spatial_data_comparison,
    plot_spatial_data_histograms,
    plot_spatial_features,
)

# Training plots
from arcadia.plotting.training import (
    plot_archetype_vs_latent_distances,
    plot_batch_specific_umaps,
    plot_cell_type_distributions,
    plot_cell_type_prediction_confusion_matrix,
    plot_cn_prediction_confusion_matrix,
    plot_cn_prediction_per_cell_type,
    plot_combined_latent_space,
    plot_counterfactual_comparison,
    plot_counterfactual_comparison_with_suffix,
    plot_encoded_latent_space_comparison,
    plot_latent_distances,
    plot_latent_mean_std_legacy,
    plot_latent_pca_both_modalities_by_celltype,
    plot_latent_pca_both_modalities_cn,
    plot_latent_single,
    plot_losses,
    plot_normalized_losses,
    plot_pca_umap_latent_space_during_train,
    plot_pre_training_visualizations,
    plot_rna_protein_latent_cn_cell_type_umap,
    plot_similarity_loss_history,
    plot_train_val_normalized_losses,
    plot_training_metrics_history,
    plot_umap_with_extremes,
    plot_warmup_loss_distributions,
    pre_train_adata_histograms_heatmap,
    reconstruction_comparison_plot,
    test_plot_latent_pca_both_modalities_by_celltype,
)

__all__ = [
    # General
    "compute_opacity_per_cell_type",
    "plot_cell_type_distribution",
    "plot_data_overview",
    "plot_preprocessing_results",
    "safe_mlflow_log_figure",
    "set_consistent_cell_type_colors",
    # Preprocessing
    "plot_b_cells_analysis",
    "plot_batch_correction_after",
    "plot_batch_correction_before",
    "plot_count_distribution",
    "plot_expression_heatmap",
    "plot_expression_heatmaps",
    "plot_extreme_archetype_confusion",
    "plot_final_alignment_results",
    "plot_gene_variance_elbow",
    "plot_kneedle_analysis",
    "plot_merged_dataset_analysis",
    "plot_original_data_umaps",
    "plot_original_data_visualizations",
    "plot_pca_and_umap",
    "plot_protein_analysis",
    "plot_protein_umap",
    "plot_protein_violin",
    "plot_spatial_distance_hist",
    "plot_spatial_locations",
    "plot_spatial_only_umap",
    "plot_umap_visualizations_original_data",
    "plot_variance_analysis_processed",
    "plot_variance_analysis_raw",
    # Archetypes
    "plot_archetype_embedding",
    "plot_archetype_heatmaps",
    "plot_archetype_proportions",
    "plot_archetype_visualizations",
    "plot_archetype_vs_latent_distances",
    "plot_archetype_weights",
    "plot_batch_archetype_visualization",
    "plot_cn_features_correlation",
    "plot_cross_modal_archetype_similarity_matrix",
    "plot_extreme_archetypes_alignment",
    # Training
    "plot_cell_type_distributions",
    "plot_cell_type_prediction_confusion_matrix",
    "plot_cn_prediction_confusion_matrix",
    "plot_cn_prediction_per_cell_type",
    "plot_combined_latent_space",
    "plot_counterfactual_comparison",
    "plot_counterfactual_comparison_with_suffix",
    "plot_encoded_latent_space_comparison",
    "plot_latent_distances",
    "plot_latent_mean_std_legacy",
    "plot_latent_pca_both_modalities_by_celltype",
    "plot_latent_pca_both_modalities_cn",
    "plot_latent_single",
    "plot_losses",
    "plot_normalized_losses",
    "plot_pca_umap_latent_space_during_train",
    "plot_rna_protein_latent_cn_cell_type_umap",
    "plot_similarity_loss_history",
    "plot_train_val_normalized_losses",
    "plot_training_metrics_history",
    "plot_umap_with_extremes",
    "plot_warmup_loss_distributions",
    "pre_train_adata_histograms_heatmap",
    "reconstruction_comparison_plot",
    "test_plot_latent_pca_both_modalities_by_celltype",
    # Spatial
    "plot_elbow_method",
    "plot_feature_mean_distributions",
    "plot_feature_means_line",
    "plot_feature_value_distributions",
    "plot_modality_embeddings",
    "plot_protein_cn_subset_umaps",
    "plot_protein_vs_cn_statistics",
    "plot_spatial_clusters",
    "plot_spatial_data",
    "plot_spatial_data_comparison",
    "plot_spatial_data_histograms",
    "plot_spatial_features",
    # Training
    "plot_batch_specific_umaps",
    "plot_pre_training_visualizations",
    # Post-hoc
    "generate_cn_umap_plots",
    "plot_counterfactual_distribution_histograms",
    "plot_grouped_metrics",
    "plot_individual_and_combined_umaps",
    "plot_latent_space_mixing",
    "plot_metrics_by_cell_type",
    "plot_morans_i",
    "plot_same_modal_vs_counterfactual_rna_differential_expression_and_umap",
    "plot_umap_latent_arcadia",
]
